### ISSUE TITLE
More precise exceptions

### ISSUE THREAD

**Issue by erickskrauch** [emarref/jwt#17]
My suggestion is to organize a more precise exceptions for JWT verification.

For example: [\Emarref\Jwt\Verification\ExpirationVerifier:45](https://github.com/emarref/jwt/blob/558e9944e1f15cb46e956ca70f14cbef1d9d730a/src/Verification/ExpirationVerifier.php#L45) should throw `ExpiredException`, which should be inherited from base [\Emarref\Jwt\Exception\VerificationException](https://github.com/emarref/jwt/blob/558e9944e1f15cb46e956ca70f14cbef1d9d730a/src/Exception/VerificationException.php). And so with all verifiers.

I can prepare a PR, if you think it is necessary in the main repository (in my project it needed).

**Comment by erickskrauch** [comment]
Okay, I did not wait for an answer and began to work on this task :D

**Comment by erickskrauch** [comment]
https://github.com/emarref/jwt/pull/18

**Comment by emarref** [comment]
#19

**Comment by emarref** [comment]
Fixed in v1.0.2 by #18.
