### ISSUE TITLE
get $token value easily

### ISSUE THREAD

**Issue by iyasilias** [emarref/jwt#25]
Hi, after `$token = $jwt->deserialize($serializedToken);` I would like to get the $token value easily as the content is not only for claims verification but to pass some data for use. Something like` $token->addClaim(new Claim\PrivateClaim('claim_name', 'claim_value'));` which can be access like `print $token->claim_name` and will produce `claim_value`.

**Comment by iyasilias** [comment]
Found in Using RS256 Encryption documentation:
`$t = json_decode($token->getPayload()->jsonSerialize());`

`print $t->claim_name //result: claim_value`

**Comment by emarref** [comment]
I'm generally not a fan of magic accessors etc, however the `PropertyList` class is a good candidate for this functionality. I'd be more inclined to offer the interface as `$token->getPayload()->claim_name`. It could potentially offer `ArrayAccess` functionality too, as `$token->getPayload()['claim_name']`. Will keep it in mind for a future release.
