### ISSUE TITLE
Documentation addClaim()

### ISSUE THREAD

**Issue by normance** [emarref/jwt#28]
The readme states:
use Emarref\Jwt\Claim;
$token = new Emarref\Jwt\Token();
$token->addClaim(new Claim\Audience(['audience_1', 'audience_2']));
...
But I get a fatal error "Trait 'Emarref\Jwt\Claim' not found"

My solution: 
remove  "use Emarref\Jwt\Claim;"
change  $token->addClaim(new Claim\Audience( ... ));
into     $token->addClaim(new Emarref\Jwt\Claim\Audience( ... ));

**Comment by emarref** [comment]
The `use Emarref\Jwt\Claim;` statement should be outside of any class, at the top of the file. From the fatal error you've mentioned, it sounds like you might be attempting to import that Claim namespace inside a class, which also uses the `use` keyword for traits.

E.g. importing a namespace:

```
<?php

use Emarref\Jwt\Claim; // Imports a namespace
new Claim\Audience(); // Works fine
```

compared with:

```
<?php

class MyClass {
    use Emarref\Jwt\Claim; // Uses a trait.
    new Claim\Audience(); // Will cause a fatal error.
}
```

Are you able to please confirm the context in which you are importing the Claim namespace?

**Comment by normance** [comment]
My mistake :(

You are right and thank you for your support. I hope your answer could help someone else so you won’t have wasted your time.

Regards

Le 27 mars 2017 à 22:18, Malcolm <notifications@github.com> a écrit :

The use Emarref\Jwt\Claim; statement should be outside of any class, at the top of the file. From the fatal error you've mentioned, it sounds like you might be attempting to import that Claim namespace inside a class, which also uses the use keyword for traits.

E.g. importing a namespace:

<?php

use Emarref\Jwt\Claim; // Imports a namespace
new Claim\Audience(); // Works fine
compared with:

<?php

class MyClass {
    use Emarref\Jwt\Claim; // Uses a trait.
    new Claim\Audience(); // Will cause a fatal error.
}
Are you able to please confirm the context in which you are importing the Claim namespace?

**Comment by emarref** [comment]
No problem.
