### ISSUE TITLE
How can I add the payload? 

### ISSUE THREAD

**Issue by waynegemmell** [emarref/jwt#31]
Hi

I can see that there is a getPayload function. How do I add a payload though. 

Thanks!

**Comment by emarref** [comment]
You use `addClaim()`.

A payload is a collection of claims. There are [registered claim names](http://self-issued.info/docs/draft-ietf-oauth-json-web-token.html#RegisteredClaimName) (e.g. `sub`) and custom public/private claims, which can be whatever you want.

```
$token = new Emarref\Jwt\Token();
$token->addClaim(new Claim\Subject('your_subject')); // Adds the subject `sub` claim
$token->addClaim(new Claim\PublicClaim('sub', 'your_subject')); // Analogous to the above
$token->addClaim(new Claim\PublicClaim('any_thing_i_want', 'foo'));
```

The above would result in the following payload:

```
{"sub":"your_subject","anything_i_want":"foo"}
```
