### ISSUE TITLE
Verifying the Private Claims

### ISSUE THREAD

**Issue by sguddati** [emarref/jwt#9]
How do we verify the private Claim values in the returned token? Context object is only covering the registered values, but not the private claim values. Can you please elaborate?

**Comment by emarref** [comment]
As private claims are arbitrary, you will need to override the `Jwt#getVerifiers()` method to return a custom verifier. E.g.

```php
// MyJwt.php
class MyJwt extends Emarref\Jwt\Jwt
{
    protected function getVerifiers(\Emarref\Jwt\Verification\Context $context)
    {
        $verifiers = parent::getVerifiers($context);

        $verifiers[] = new MyVerifier();

        return $verifiers;
    }
}
```

```php
// MyVerifier.php
class MyVerifier implements \Emarref\Jwt\Verification\VerifierInterface
{
    public function verify(\Emarref\Jwt\Token $token)
    {
        $myClaim = $token->getPayload()->findClaimByName('my_claim')->getValue();

        // Do something with the value.

        throw new \Emarref\Jwt\Exception\VerificationException(sprintf('Cannot verify my_claim with value "%s".', $myClaim));
    }
}
```

Then the usage would look something like this:

```php
$token = new Emarref\Jwt\Token();
$token->addClaim(new \Emarref\Jwt\Claim\PrivateClaim('my_claim', 'my_value'));

$jwt = new MyJwt();
// Configure encryption etc then verify as per usual.
$context = new Emarref\Jwt\Verification\Context($encryption);

try {
    $jwt->verify($token, $context);
} catch (Emarref\Jwt\Exception\VerificationException $e) {
    // Handle the verification exception
}
```

If your claim relies on some other value for verification, your verifier could have some service injected to provide that value, or alternatively, if that value is needed in several places, you could override the context class with a new getter/setter combo then use that in your verifier.

Does that make sense?

**Comment by sguddati** [comment]
Yes .. Thank you .. will try this out. 
Srinivas.
